# Railway configuration for Java 21
[providers]
java = "21"

[phases.setup]
cmds = ["chmod +x mvnw"]

[variables]
JAVA_VERSION = "21"
MAVEN_OPTS = "-Xmx1024m"
JAVA_TOOL_OPTIONS = "-Xmx512m -XX:+UseContainerSupport"

[phases.build]
cmds = ["./mvnw clean package -DskipTests -q"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/qoder-v3-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
JAVA_TOOL_OPTIONS = "-Xmx512m -XX:+UseContainerSupport"